plotWeb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from plots import views

urlpatterns = [
    path('plots/', include('plots.urls')),
    path('', views.maindomain, name='maindomain'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plots/urls.py
from django.urls import path

from . import views

app_name = 'plots'

urlpatterns = [
    path('', views.home, name='Home'),
    path('resultsplot/', views.resultsplot, name='resultsplot'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('profile', views.profile, name='profile'),
    path('registrar/', views.signup, name='registrar'),
    path('logout/', views.logoutview, name='logout'),
    path('user_login/', views.user_login, name='user_login'),
    path('post/<int:post_id>/', views.post_view, name='post'),
    path('posts/', views.list_of_post, name='list_post'),
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>', views.delete_post, name='delete_post'),
    path('new_post/', views.new_post, name='new_post'),
]

plots/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

genero = (
    ('Hombre', 'Hombre'),
    ('Mujer', 'Mujer'),
)


class UserModel(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    avatar = models.ImageField(upload_to='plots', default='plots/default.png')
    location = models.CharField(max_length=140)
    gender = models.CharField(max_length=140, choices=genero)
    information = models.TextField()

    def __str__(self):
        return 'Usuario: {}'.format(self.username)

    def save(self, *args, **kwargs):
        try:
            this = UserModel.objects.get(id=self.id)
            if this.avatar != self.avatar:
                this.avatar.delete(save=False)
        except:
            pass
        super(UserModel, self).save(*args, **kwargs)


class Post(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    title = models.CharField(max_length=140)
    post_text = models.TextField()
    post_date = models.DateTimeField(editable=False)
    post_modified = models.DateTimeField(editable=False)

    def __str__(self):
        return (
            f'Post de {self.user.username:<40} - Titulo: {self.title:>60} - Ultima modificacion:'
            f' {self.post_date}'
        )

    def save(self, *args, **kwargs):
        if not self.id:
            self.post_date = timezone.now()
        self.post_modified = timezone.now()
        return super(Post, self).save(*args, **kwargs)

plots/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
                                       UsernameField)
from django.contrib.auth.models import User
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from .models import Post, UserModel


class DataForm(forms.Form):
    
    x_points = forms.CharField(
        label='Puntos de X', 
        max_length=200, 
        widget=forms.TextInput(
            attrs={
                'placeholder': '[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]'
                }
            )
        )
    
    y_points = forms.CharField(
        label='Puntos de Y', 
        max_length=200, 
        widget=forms.TextInput(
            attrs={
                'placeholder': '[0, 1, 1.5, 1.8, 2, 2.1, 2.15, 2.17, 2.18, 2.185]'
                }
            )
        )


class RegistrationForm(forms.ModelForm):
    
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'validate'
                }
            ),
        )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'validate'
                }
            ),
        )
    
    class Meta:
        model = UserModel
        fields = (
            'username', 'first_name', 'last_name',
            'email', 'password1', 'password2'
            )

        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'validate',
                    }
                ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'validate',
                    }
                ),
            'first_name': forms.TextInput(
                attrs={
                    'class': 'validate',
                    }
                ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'validate',
                    }
                )
            }

        labels = {
            'email': 'Correo electronico',
            'first_name': 'Nombre (opcional)',
            'last_name': 'Apellido (opcional)',
        }

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = False
        self.fields['last_name'].required = False
        self.fields['email'].required = True
        self.fields['password1'].required = True
        self.fields['password2'].required = True

        self.fields['password1'].widget = forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'validate'
                }
            )

        self.fields['password2'].widget = forms.PasswordInput(
            attrs={
                'autocomplete': 'new-password',
                'class': 'validate'
                }
            )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()

        return user


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        
        self.fields['username'].widget = forms.TextInput(
            attrs={
                'autofocus': True,
                'placeholder': 'usuario'
                }
            )
        
        self.fields['password'].widget = forms.PasswordInput(
            attrs={
                'autocomplete': 'current-password', 
                'placeholder': 'Contraseña'
                }
            )


class EditProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = False
        self.fields['last_name'].required = False
        self.fields['email'].required = True
        self.fields['location'].required = False
        self.fields['gender'].required = False
        self.fields['information'].required = False

    class Meta:
        model = UserModel
        fields = (
            'avatar', 'first_name', 'last_name',
            'email', 'location', 'gender', 
            'information'
            )

        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Primer nombre'
                    }
                ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Primer apellido'
                    }
                ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'validate', 'placeholder': 'correo@mail.com'
                    }
                ),
            'location': forms.TextInput(
                attrs={
                    'placeholder': 'Pais, ciudad y/o estado'
                    }
                ),
            'information': forms.Textarea(
                attrs={
                    'class': 'materialize-textarea',
                    'placeholder': 'Cualquier informacion adicional'
                    }
                ),
            'gender': forms.Select(
                attrs={
                    'class': 'light-blue-text text-accent-4'
                    }
                ),
            }

        labels = {
            "avatar": "Avatar",
            "first_name": "Nombre",
            "last_name": "Apellido",
            "email": "Correo electronico",
            "location": "Localizacion",
            "gender": "Genero",
            "information": "Informacion",
        }


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = True

    class Meta:
        model = Post
        fields = {'title', 'post_text'}

        widgets = {
            'post_text': forms.Textarea(attrs={
                'class': 'materialize-textarea', 'placeholder': 'Contenido del post...'
            }),
            'title': forms.TextInput(attrs={'placeholder': 'Titulo del post'})
        }

        labels = {
            'title': 'Titulo',
            'post_text': 'Contenido del post',
        }

plots/views.py
import json

from bokeh import plotting as plt
from bokeh.embed import components
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

from .forms import (DataForm, EditProfileForm, PostForm, RegistrationForm,
                    UserLoginForm)
from .models import Post, UserModel


def maindomain(request):
    return redirect('plots:Home')


def home(request):
    return render(request, 'plots/home.html')


@login_required
def resultsplot(request):
    if request.method == 'POST':
        data = request.POST
        x_data = json.loads(data['x_points'])
        y_data = json.loads(data['y_points'])

        p = plt.figure(sizing_mode='scale_width')
        p.line(x_data, y_data)

        script_bok, div_bok = components(p)

        return HttpResponse([script_bok, div_bok])
    else:
        form = DataForm()
        x_data = [0]
        y_data = [0]

        p = plt.figure(sizing_mode='scale_width')
        p.line(x_data, y_data)
        script_bok, div_bok = components(p)

        return render(request, 'plots/resultsplot.html', context={
            'form': form,
            'div_bok': div_bok,
            'script_bok': script_bok
        })


def signup(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('plots:Home')
    elif request.is_ajax():
        if request.GET.get('tipo') == 'username':
            data = {
                'flag': UserModel.objects.filter(username=request.GET.get('name', None)).exists()
            }
        elif request.GET.get('tipo') == 'email':
            try:
                validate_email(request.GET.get('email', None))
                if UserModel.objects.filter(email=request.GET.get('email', None)).exists():
                    data = {
                        'flag': False,
                        'info': 'Correo electronico ya registrado, ingrese otro',
                    }
                else:
                    data = {
                        'flag': True,
                        'info': '',
                    }
            except ValidationError as e:
                data = {
                    'flag': False,
                    'info': 'Ingrese una dirección de correo electrónico válida.',
                }                
        return JsonResponse(data)
    else: 
        form = RegistrationForm()

    return render(request, 'plots/registrar.html', {'form': form})


# def username_validation(request):
#     print('holas')
#     return HttpResponse('succes')


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)

            if request.POST.get('next', None):
                return redirect(request.POST['next'])
            else:
                return redirect('plots:Home')
    else:
        form = UserLoginForm()
    return render(request, 'plots/user_login.html', {'form': form})


@login_required
def logoutview(request):
    logout(request)
    return redirect('plots:Home')


@login_required
def profile(request):
    usuario = UserModel.objects.get(username=request.user.username)
    post_object = Post.objects.filter(user=request.user)
    post_list = [item for item in post_object]
    return render(request, 'plots/profile.html', {
        'usuario': usuario,
        'post_list': post_list
    })


@login_required
def edit_profile(request):
    if request.method == 'POST':
        usuario = UserModel.objects.get(username=request.user.username)
        perfilForm = EditProfileForm(
            request.POST, 
            request.FILES, 
            instance=usuario
            )

        if perfilForm.is_valid():
            perfilForm.save()
            return redirect('plots:profile')
        else:
            return render(request, 'plots/edit_profile.html', {
                'perfilForm': perfilForm
            })
    else:
        usuario = UserModel.objects.get(username=request.user.username)
        perfilForm = EditProfileForm(instance=usuario)
        return render(request, 'plots/edit_profile.html', {
            'perfilForm': perfilForm
        })


@login_required
def list_of_post(request):
    post_object = Post.objects.filter(user=request.user)
    post_list = [item for item in post_object]
    return render(request, 'plots/list_post.html', context={'post_list': post_list})


@login_required
def post_view(request, post_id):
    post = Post.objects.get(pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'plots/post_template.html', context=context)


@login_required
def edit_post(request, post_id):
    if request.method == 'POST':

        post = Post.objects.get(pk=post_id)
        post_form = PostForm(request.POST, instance=post)

        if post_form.is_valid():
            post_form.save()
            post = Post.objects.get(pk=post_id)

            return redirect('plots:post', post_id=post_id)
        else:
            return render(request, 'plots/edit_post.html', {
                'post_form': post_form,
                'post': post,
            })
    else:
        post = Post.objects.get(pk=post_id)
        post_form = PostForm(instance=post)
        return render(request, 'plots/edit_post.html', {
            'post_form': post_form,
            'post': post,
        })


@login_required
def delete_post(request, post_id):
    if request.method == 'POST':
        post = Post.objects.get(pk=post_id)
        post.delete()
        return redirect('plots:profile')
    else:
        return redirect('plots:Home')


@login_required
def new_post(request):
    if request.method == 'POST':
        post = Post(user=request.user)
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post = post_form.save()
            return redirect('plots:post', post_id=post.id)
        else:
            return render(request, 'plots/new_post.html', {
                'post_form': post_form,
            })
    else:
        post_form = PostForm()
        return render(request, 'plots/new_post.html', {
            'post_form': post_form,
        })

plots/templates/plots/base.html
<!DOCTYPE html>
<html lang="es">

<head>

  {% load static %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Pagina boleta</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/materialicons.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/materialize.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}">

  {% block cssContent %}
  {% endblock cssContent %}

</head>

<body>
  <main>
    <header>
      <div class="navbar-fixed">
        <nav>
          {% if user.is_authenticated %}
          <ul id="dropdown1" class="dropdown-content">
            <li><a href="{% url 'plots:list_post' %}" class="light-blue-text text-accent-4">Mis post</a></li>
            <li><a href="{% url 'plots:profile' %}" class="light-blue-text text-accent-4">Perfil</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'plots:logout'%}" class="light-blue-text text-accent-4">Cerrar session</a></li>
          </ul>
          {% endif %}
          <div class="nav-wrapper light-blue accent-4">
            <a href="{% url 'plots:Home' %}" class="brand-logo">Intento de pagina</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            {% if user.is_anonymous %}
            <ul class="right hide-on-med-and-down">
              <li><a href="{% url 'plots:resultsplot' %}">Ploting</a></li>
              <li><a href="{% url 'plots:registrar'%}">registrarse</a></li>
              <li><a href="{% url 'plots:user_login' %}">login</a></li>
            </ul>
            {% else %}
            <ul class="right hide-on-med-and-down">
              <li><a href="{% url 'plots:resultsplot' %}">Ploting</a></li>
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{{user.username}}</a></li>
            </ul>
            {% endif %}
          </div>
        </nav>
      </div>

      {% if user.is_anonymous %}
      <ul class="sidenav sidenav-fixed invesible-top col l1" id="mobile-demo">
        <li><a href="{% url 'plots:resultsplot' %}">Ploting</a></li>
        <li><a href="{% url 'plots:registrar'%}">registrarse</a></li>
        <li><a href="{% url 'plots:user_login' %}">login</a></li>
      </ul>
      {% else %}
      <ul class="sidenav sidenav-fixed invesible-top" id="mobile-demo">
        <li><a href="{% url 'plots:resultsplot' %}" style="color: #0a0d1a;">Ploting</a></li>
        <li><a href="{% url 'plots:list_post' %}">Mis post</a></li>
        <li>
          <ul class="collapsible collapsible-accordion">
            <li>
              <a class="collapsible-header" tabindex="0">{{user.username}}</a>
              <div class="collapsible-body">
                <ul>
                  <li>
                    <a href="{% url 'plots:profile' %}">Ver perfil</a>
                  </li>
                  <li>
                    <a href="{% url 'plots:edit_profile' %}">Editar perfil</a>
                  </li>
                </ul>
              </div>
            </li>
          </ul>
        </li>
        <li><a href="{% url 'plots:logout'%}">Cerrar session</a></li>
      </ul>
      {% endif %}
    </header>

    <div class="row content_margin">
      <div class="container">
        <div class="col s12 m12 l12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>

  </main>

  <script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/materialize.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>

  {% block scriptsContent %}
  {% endblock scriptsContent %}

</body>

</html>

plots/templates/plots/edit_post.html
{% extends "plots/base.html" %}

{% block cssContent %}
{% endblock cssContent %}

{% block content %}

<div class="row">
  <div class="col s12 m10 l8 offset-m1 offset-l2">
    <div class="card-panel hoverable ">
      <div class="row">
        <form action="{% url 'plots:edit_post' post.id %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="col s12 m12 l12">

            <div class="input-field">
              <i class="material-icons prefix">title</i>
              <label for="{{ post_form.title.auto_id }}" class="active">{{ post_form.title.label }}</label>
              {{ post_form.title }}
              {% if post_form.title.errors %}
              <ul style="margin-top: 0px; margin-bottom: 0px;">
                {% for error in post_form.title.errors %}
                <li><span class="red-text text-darken-1">{{ error }}</span></li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>

            <div class="input-field" style="margin-top: 40px;">
              <i class="material-icons prefix">view_headline</i>
              <label for="{{ post_form.post_text.auto_id }}" class="active">{{ post_form.post_text.label }}</label>
              {{ post_form.post_text }}
            </div>

            <div class="row right-align">
              <div class="col s12" style="margin-bottom: -35px;">
                <a href="{{ request.META.HTTP_REFERER }}" class="btn waves-effect waves-light red darken-1">cancelar<i
                    class="material-icons right">cancel</i></a>
                <button type="submit" class="btn waves-effect waves-light light-blue accent-4">Guardar<i
                    class="material-icons right">save</i></button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block scriptsContent %}
{% endblock scriptsContent %}

plots/templates/plots/edit_profile.html
{% extends 'plots/base.html' %}

{% block cssContent %}
{% endblock cssContent %}

{% block content %}

<div class="row">
  <div class="col s12 m10 l8 offset-m1 offset-l2">
    <div class="card-panel hoverable ">
      <div class="row">
        <form action="{% url 'plots:edit_profile' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="col s12 m12 l5 center-align">
            <div class="col s12 center-align">
              <img id="imgEdit" src="{{perfilForm.instance.avatar.url}}" class="circle responsive-img"
                style="height:150px; width: 150px;" />
            </div>
            <label for="id_avatar" class="btn waves-effect waves-light light-blue accent-4"><i
                class="material-icons left">camera_alt</i>Cambiar</label>
            <div class="col s12 center-align">
              <div class="file-field input-field">
                <div class="file-path-wrapper">
                  <input input type="file" name="avatar" accept="image/*" id="id_avatar">
                </div>
              </div>
            </div>
          </div>
          <div class="col s12 m12 l7">

            <div class="input-field">
              <i class="material-icons prefix">person</i>
              <label for="{{ perfilForm.first_name.auto_id }}" class="active">{{ perfilForm.first_name.label }}</label>
              {{ perfilForm.first_name }}
            </div>

            <div class="input-field">
              <i class="material-icons prefix">person_add</i>
              <label for="{{ perfilForm.last_name.auto_id }}" class="active">{{ perfilForm.last_name.label }}</label>
              {{ perfilForm.last_name }}
            </div>

            <div class="input-field">
              <i class="material-icons prefix">mail_outline</i>
              <label for="{{ perfilForm.email.auto_id }}" class="active">{{ perfilForm.email.label }}</label>
              {{ perfilForm.email }}
              {% if perfilForm.email.errors %}
              <ul style="margin-top: 0px; margin-bottom: 0px;">
                {% for error in perfilForm.email.errors %}
                <li><span class="invalido" style="display: block;"><i
                      class="material-icons">cancel</i> {{ error }}</span></li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>

          </div>
          <div class="col s12 m12 l12">

            <div class="input-field" style="margin-bottom: 23px; margin-top: 0px;">
              <i class="material-icons prefix">wc</i>
              {{ perfilForm.gender }}
              <label for="{{ perfilForm.gender.auto_id }}">{{ perfilForm.gender.label }}</label>
            </div>

            <div class="input-field">
              <i class="material-icons prefix">location_city</i>
              <label for="{{ perfilForm.location.auto_id }}" class="active">{{ perfilForm.location.label }}</label>
              {{ perfilForm.location }}
            </div>

            <div class="input-field">
              <i class="material-icons prefix">info</i>
              <label for="{{ perfilForm.information.auto_id }}"
                class="active">{{ perfilForm.information.label }}</label>
              {{ perfilForm.information }}
            </div>

            {% if perfilForm.avatar.errors %}
            {% for error in perfilForm.avatar.errors %}
            <p for="errorimage" class="active red-text text-darken-1" style="margin-top: -10px;"><i
                class="material-icons small" style="margin-right: 10px; margin-top: -10px">warning</i>
              {{ error }}</p>
            {% endfor %}
            {% endif %}


            <div class="row right-align">
              <div class="col s12" style="margin-bottom: -35px;">
                <a href="{% url 'plots:profile' %}" class="btn waves-effect waves-light red darken-1">cancelar<i
                    class="material-icons right">cancel</i></a>
                <button type="submit" class="btn waves-effect waves-light light-blue accent-4">Guardar<i
                    class="material-icons right">save</i></button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block scriptsContent %}
{% endblock scriptsContent %}

plots/templates/plots/home.html
{% extends "plots/base.html" %}

{% block cssContent %}
{% endblock cssContent %}

{% block content %}
  
<div class="row">
  <div class="card-panel hoverable col s12 m12 l12">
    <div class="carousel carousel-slider center">
      <div class="carousel-item" href="#one!">
        <h2>Primer Panel</h2>
        <p>Probando paneles D:!</p>
      </div>
      <div class="carousel-item" href="#two!">
        <h2>Segundo Panel</h2>
        <p>Probando paneles D:!</p>
      </div>
      <div class="carousel-item" href="#three!">
        <h2>Tercer Panel</h2>
        {% if user.is_authenticated %}
        <a href="{% url 'plots:resultsplot' %}" class="btn waves-effect waves-light light-blue accent-4">ploting</a>
        {% else %}
        <a href="{% url 'plots:user_login' %}" class="btn waves-effect waves-light light-blue accent-4">Login</a>
        {% endif %}

      </div>
      <div class="carousel-item" href="#four!">
        <h2>Fourth Panel</h2>
        <p>This is your fourth panel</p>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

{% block scriptsContent %}
{% endblock scriptsContent %}

plots/templates/plots/profile.html
{% extends 'plots/base.html' %}

{% block cssContent %}
{% endblock cssContent %}

{% block content %}

<div class="row">
  <div class="col s12 m12 l7">
    <div class="card-panel">
      <div class="row">
        <div class="col s12 5 l5 center">
          <img src="{{MEDIA_URL}}{{usuario.avatar}}" class="circle responsive-img" style="height:150px; width: 150px;" />
          <p class="flow-text">{{usuario.username}}</p>
        </div>
        <div class="col s12 m7 l7">
          <p class="flow-text" style="font-size: 14pt;"><i class="material-icons">person</i>
            {{usuario.first_name}} {{usuario.last_name}}</p>
          <p class="flow-text" style="font-size: 14pt;"><i class="material-icons">mail_outline</i>
            {{usuario.email}}</p>
          <p class="flow-text" style="font-size: 14pt;"><i class="material-icons">wc</i> {{usuario.gender}}</p>
          <p class="flow-text" style="font-size: 14pt;"><i class="material-icons">location_city</i> {{usuario.location}}
          </p>
          <p class="flow-text" style="font-size: 14pt;"><i class="material-icons">info</i> {{usuario.information}}</p>
          <div class="row center-align">
            <div class="col s12" style="margin-bottom: -35px;">
              <a href="{% url 'plots:edit_profile' %}" class="btn waves-effect waves-light light-blue accent-4">Editar
                perfil <i class="material-icons right">edit</i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col s12 m12 l5">
    <ul class="collection with-header">
      <li class="collection-header">
        <h4 class="center">Post realizados</h4>
      </li>
      {% for post in post_list %}
      <li class="collection-item">
        <div class="truncate">
          {{post.title}}
          <div>
            <a href="#modal{{post.id}}" class="secondary-content red-text text-darken-1 modal-trigger"><i
                class="material-icons icon-separation2">delete</i><a href="{% url 'plots:edit_post' post.id %}"
                class="secondary-content light-blue-text text-accent-4"><i
                  class="material-icons icon-separation">edit</i></a></a><a href="{% url 'plots:post' post.id %}"
              class="secondary-content light-blue-text text-accent-4"><i
                class="material-icons icon-separation">visibility</i></a>
          </div>
        </div>
      </li>

      <!-- Modal Structure -->
      <div id="modal{{post.id}}" class="modal">
        <div class="modal-content">
          <h4 class="center">Confirmacion de borrado</h4>
          <h5 class="center">¿Esta seguro que desea borrar este post?</h5>
          <p><strong>Titulo:</strong> {{post.title}}</p>
          <p><strong>Fecha de creacion:</strong> {{post.post_date}}</p>
          <p><strong>Ultima modificacion:</strong> {{post.post_modified}}</p>

        </div>
        <div class="modal-footer">
          <form action="{% url 'plots:delete_post' post.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="modal-close btn waves-effect waves-light red darken-1">Borrar</button>
            <a href="#!" class="modal-close btn-flat">Cancelar</a>
          </form>
        </div>
      </div>
      {% endfor %}
    </ul>

    <div class="row right-align">
      <div class="col s12">
        <a href="{% url 'plots:new_post' %}" class="btn waves-effect waves-light light-blue accent-4">Nuevo post<i
            class="material-icons right">add</i></a>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block scriptsContent %}
{% endblock scriptsContent %}